CREATE DATABASE IF NOT EXISTS tmlibrary DEFAULT CHARACTER SET utf8mb4;
USE tmlibrary;

CREATE TABLE IF NOT EXISTS book (
    id          SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title       VARCHAR(200)  NOT NULL,
    author      VARCHAR(100)  NOT NULL,
    isbn        VARCHAR(20)   NOT NULL UNIQUE,
    price       DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    published_date DATE          NOT NULL,
    stock_quantity       INT           NOT NULL DEFAULT 0,
    created_time DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
